lib/hello_web/router.ex
# The main hubs of Phoenix apps.
# Match HTTP requests to controller actions,
# wire up real-time channel handlers,
# and define a series of pipeline transfromations scoped to a set of routes

defmodule HelloWeb.Router do
  use HelloWeb, :router

  pipeline :browser do
    plug :accepts, ["html", "text"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HelloWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :fetch_current_cart
    plug HelloWeb.Plugs.Locale, "en"
  end

  defp fetch_current_user(conn, _) do
    if user_uuid = get_session(conn, :current_uuid) do
      assign(conn, :current_uuid, user_uuid)
    else
      new_uuid = Ecto.UUID.generate()

      conn
      |> assign(:current_uuid, new_uuid)
      |> put_session(:current_uuid, new_uuid)
    end
  end

  alias Hello.ShoppingCart

  def fetch_current_cart(conn, _opts) do
    if cart = ShoppingCart.get_cart_by_user_uuid(conn.assigns.current_uuid) do
      assign(conn, :cart, cart)
    else
      {:ok, new_cart} = ShoppingCart.create_cart(conn.assigns.current_uuid)
      assign(conn, :cart, new_cart)
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Verb/path pairs are mapped to controllers.
  # The controller then tells a view to render a template.
  scope "/", HelloWeb do
    pipe_through :browser

    # The :index, and :show are considered `action`s
    # It is the controllers job to define functions for these actions
    get "/", PageController, :index

    resources "/orders", OrderController, only: [:create, :show]

    resources "/products", ProductController

    resources "/cart_items", CartItemController, only: [:create, :delete]

    get "/cart", CartController, :show
    put "/cart", CartController, :update

    get "/redirect_test", PageController, :redirect_test

    get "/hello", HelloController, :index
    get "/hello/:messenger", HelloController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: HelloWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/hello_web/views/layout_view.ex
# Functions defined here can be called in the respective template,
# because all templates are effectively compiled into functions inside their respective view
defmodule HelloWeb.LayoutView do
  use HelloWeb, :view

  def title() do
    "Awesome title!"
  end

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/hello_web/templates/layout/admin.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tag() %>
    <%= live_title_tag(assigns[:page_title] || "Hello", suffix: " · Phoenix Framework") %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>
  </head>

  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li>
                <%= link("LiveDashboard", to: Routes.live_dashboard_path(@conn, :home)) %>
              </li>
            <% end %>
          </ul>
        </nav>
        <p>Administration</p>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/hello_web/templates/layout/app.html.heex
<main class="container">
  <p>Locale: <%= @locale %></p>
  <p class="alert alert-info" role="alert">
    <%= get_flash(@conn, :info) %>
  </p>
  <p class="alert alert-danger" role="alert">
    <%= get_flash(@conn, :error) %>
  </p>
  <div>
    <!-- Routes.page_path path helper can be used because the alias in `def controller do` in `hello_web.ex` -->
    <%= link("welcome page", to: Routes.page_path(@conn, :index)) %>
  </div>

  <%= link("hello page", to: Routes.hello_path(@conn, :index)) %>

  <%= @inner_content %>
</main>

lib/hello_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
    <%= live_flash(@flash, :info) %>
  </p>

  <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
    <%= live_flash(@flash, :error) %>
  </p>

  <%= @inner_content %>
</main>

lib/hello_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tag() %>
    <title>
      <%= title() %>
    </title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>
  </head>

  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li>
                <%= link("LiveDashboard", to: Routes.live_dashboard_path(@conn, :home)) %>
              </li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img
            src={Routes.static_path(@conn, "/images/phoenix.png")}
            alt="Phoenix Framework Logo"
          />
        </a>
      </section>
      <%= Phoenix.View.render(HelloWeb.PageView, "test.html", message: "Hello from layout!") %>
    </header>

    <%= @inner_content %>
  </body>
</html>